# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UsoQTableWidgetDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UsoTableWidgetDialog(object):
    def setupUi(self, UsoTableWidgetDialog):
        UsoTableWidgetDialog.setObjectName("UsoTableWidgetDialog")
        UsoTableWidgetDialog.resize(429, 636)
        self.verticalLayout = QtWidgets.QVBoxLayout(UsoTableWidgetDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbl_linguagens = QtWidgets.QTableWidget(UsoTableWidgetDialog)
        self.tbl_linguagens.setObjectName("tbl_linguagens")
        self.tbl_linguagens.setColumnCount(2)
        self.tbl_linguagens.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_linguagens.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_linguagens.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tbl_linguagens)

        self.retranslateUi(UsoTableWidgetDialog)
        QtCore.QMetaObject.connectSlotsByName(UsoTableWidgetDialog)

    def retranslateUi(self, UsoTableWidgetDialog):
        _translate = QtCore.QCoreApplication.translate
        UsoTableWidgetDialog.setWindowTitle(_translate("UsoTableWidgetDialog", "Uso do Componente QTableWidget"))
        item = self.tbl_linguagens.horizontalHeaderItem(0)
        item.setText(_translate("UsoTableWidgetDialog", "Linguagem"))
        item = self.tbl_linguagens.horizontalHeaderItem(1)
        item.setText(_translate("UsoTableWidgetDialog", "Versão"))
